<?php

error_reporting(-1);
ini_set('display_errors', 1);

/**
 * Autoload for local classes generated by the WSDL2PHP process.
 *
 * @param string $className The class to be loaded
 */
function autoloaderForWSDL($className)
{
    $className = ltrim($className, '\\');
    $fileName = '';
    $namespace = '';
    if ($lastNsPos = strrpos($className, '\\')) {
        $namespace = substr($className, 0, $lastNsPos);
        $className = substr($className, $lastNsPos + 1);
        $fileName = str_replace('\\', DIRECTORY_SEPARATOR, $namespace).DIRECTORY_SEPARATOR;
    }
    $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className).'.php';
    $fileName = realpath(dirname(__DIR__).'/Services/'.$fileName);

    echo 'Loading ', $fileName, ' in response to the request to use the class ', $className, PHP_EOL;

    require $fileName;
}

/*
 * Register the autoloader with SPL.
 */
spl_autoload_register('autoloaderForWSDL', false, false);

/**
 * Define the SOAP options.
 */
$a_SoapOptions = array(
    'encoding' => 'UTF-8',
    'exception' => true, // Turn SOAPFaults into Exceptions so PHP can report upon them.
    'trace' => true, // Turn on tracing so we can see EXACTLY what the headers and request/response are.
);

/**
 * As we are going to need to display XML, use Tidy to make it pretty.
 */
$a_TidyConfig = array(
    'indent' => true,
    'indent-spaces' => 4,
    'indent-attributes' => true,
    'input-xml' => true,
    'output-xml' => true,
    'wrap' => 0,
);
// $o_Tidy       = new Tidy; // Currently having issues with Tidy.

if (function_exists('Consume')) {
    list($o_Service, $o_Response, $o_SoapFault, $o_Exception) = Consume($a_SoapOptions);

    if (isset($o_Service)) {
        echo PHP_EOL,
        'Request Headers', PHP_EOL,
        '---------------', PHP_EOL,
        $o_Service->__getLastRequestHeaders(), PHP_EOL,
        'Request (XML)', PHP_EOL,
        '-------------', PHP_EOL,
            // $o_Tidy->repairString($o_Service->__getLastRequest(), $a_TidyConfig), PHP_EOL, PHP_EOL; // Currently having issues with Tidy.
        $o_Service->__getLastRequest(), PHP_EOL, PHP_EOL;
    }

    if (isset($o_Response)) {
        echo PHP_EOL,
        'Response Headers', PHP_EOL,
        '----------------', PHP_EOL,
        $o_Service->__getLastResponseHeaders(), PHP_EOL,
        'Response (XML)', PHP_EOL,
        '--------------', PHP_EOL,
            // $o_Tidy->repairString($o_Service->__getLastResponse(), $a_TidyConfig), PHP_EOL, PHP_EOL, // Currently having issues with Tidy.
        $o_Service->__getLastResponse(), PHP_EOL, PHP_EOL,
        'Interpreted Results', PHP_EOL,
        '-------------------', PHP_EOL,
        print_r($o_Response, true), PHP_EOL, PHP_EOL,
        PHP_EOL;
    }

    if (isset($o_SoapFault)) {
        echo
        'SOAP Fault', PHP_EOL,
        '----------', PHP_EOL,
        'Fault Code   : ', $o_SoapFault->faultcode, PHP_EOL,
        'Fault String : ', $o_SoapFault->faultstring, PHP_EOL,
        'Fault Detail : ', print_r($o_SoapFault->detail, true), PHP_EOL;
    }

    if (isset($o_Exception)) {
        echo
            // Show exception.
        'Exception', PHP_EOL,
        '---------', PHP_EOL,
        $e->getMessage(), PHP_EOL;
        var_dump($e);
    }

    echo PHP_EOL, 'Completed.', PHP_EOL;
}
